journpy/urls.py
from django.contrib import admin
from django.conf import settings  
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('journpys.urls')),
    path('', include('learnpython.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learnpython/urls.py
"""Defines URL patterns for the app journpys."""

from django.urls import path

from . import views

app_name = 'learnpython'
urlpatterns = [
	# Home page
	path('lessons', views.lessons, name='lessons'),
	# Page for a lesson
	path('lessons/<int:title_id>/', views.lesson, name='lesson')
]

users/urls.py
"""Defines URL patterns for users."""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
	# Include django's default auth urls.
	path('', include('django.contrib.auth.urls')),

	# Registration page.
	path('register/', views.register, name='register'),
]

learnpython/models.py
from django.db import models
from django.contrib.auth.models import User


class Title(models.Model):
	"""Title of the lesson."""
	text = models.CharField(max_length=255)
	date_added = models.DateTimeField(auto_now_add=True)


	def __str__(self):
		"""Return a string representation of the model."""
		return self.text


class Body(models.Model):
	"""Journal entry about a particular topic."""
	title = models.ForeignKey(Title, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	image1 = models.ImageField(upload_to='images/', blank=True)
	image2 = models.ImageField(upload_to='images/', blank=True)


	class Meta:
		verbose_name_plural = 'bodies'


	def __str__(self):
		"""Return a string representation of the model."""
		# Add ellipsis only if a body is longer than 70 characters
		if len(self.text) > 70:
			return f"{self.text[:70]}..."

		else:
			return self.text
			

learnpython/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Title, Body


@login_required
def lessons(request):
	"""Home page for learnpython app."""
	titles = Title.objects.order_by('date_added')
	context = {'titles': titles}
	return render(request, 'learnpython/lessons.html', context)


@login_required
def lesson(request, title_id):
	"""Display an entire lesson."""
	title = get_object_or_404(Title, id=title_id)
	bodies = title.body_set.order_by('-date_added')
	context = {'title': title, 'bodies': bodies}
	return render(request, 'learnpython/lesson.html', context)

learnpython/templates/learnpython/lesson.html
{% extends 'journpys/base.html' %}


{% block page_header %}
<h3>{{ title }}</h3>
{% endblock page_header %}

{% block content %}
{% for body in bodies %}
<div class="container-fluid">
  <img src="{{ body.image1.url }}" alt="{{ body.image1.name }}" width="100%">
</div>
<div class="card mb-3">
  <h4 class="card-header">
    {{ body.date_added|date:'M d, Y H:i' }}</h4>
  <div class="card-body">
    {{ body.text|linebreaks }}
    <img src="{{ body.image2.url }}" alt="{{ body.image2.name }}" width="100%">
  </div>
</div>

{% empty %}
<p>No lesson have been added yet.</p>
{% endfor %}

{% endblock content %}

learnpython/templates/learnpython/lessons.html
{% extends "journpys/base.html" %}

{% block page_header %}
  <h1 class="text-success"> Learn Python</h1>
  <p class="lead"> JournPy offers exciting and engaging tutorials
    that will help you learn python. Find the list of topics below
	and click on a topic to access the lesson.</p>
{% endblock page_header %}

{% block content %}
  <h2 class="text-success">Lessons</h2>
  <ol>
  	{% for title in titles %}
  	<li><h5 class="text-success"><a class="text-reset" href="{% url 'learnpython:lesson' title.id %}">{{ title }}</a></h5></li>
  	{% empty %}
  	  <li><h4>No lessons have been added yet.</h4></li>
  	{% endfor %}
  </ol>
{% endblock content %}