journpy/urls.py
from django.contrib import admin
from django.conf import settings  
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('journpys.urls')),
    path('', include('learnpython.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

journpys/urls.py
"""Defines URL patterns for the app journpys."""

from django.urls import path

from . import views

app_name = 'journpys'
urlpatterns = [
	# Home page
	path('', views.index, name='index'),

	# Page that shows all topics
	path('topics/', views.topics, name='topics'),

	# Detail page for a single topic
	path('topics/<int:topic_id>/', views.topic, name='topic'),

	# Page for adding a new topic
	path('new_topic/', views.new_topic, name='new_topic'),

	# Page for adding a new entry
	path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),

	# Page for editing an entry
	path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),

	# Page for deleting a topic and all it's entries
	path('delete_topic/<int:topic_id>/', views.delete_topic, name='delete_topic'),

	# Page for deleting an entry
	path('delete_entry/<int:entry_id>/', views.delete_entry, name='delete_entry'),

	# About page
	path('about/', views.about, name='about'),
]

learnpython/urls.py
"""Defines URL patterns for the app journpys."""

from django.urls import path

from . import views

app_name = 'learnpython'
urlpatterns = [
	# Home page
	path('lessons', views.lessons, name='lessons'),
	# Page for a lesson
	path('lessons/<int:title_id>/', views.lesson, name='lesson')
]

users/urls.py
"""Defines URL patterns for users."""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
	# Include django's default auth urls.
	path('', include('django.contrib.auth.urls')),

	# Registration page.
	path('register/', views.register, name='register'),
]

journpys/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
	"""A topic the user is learning about."""
	text = models.CharField(max_length=255)
	date_added = models.DateTimeField(auto_now_add=True)
	writer = models.ForeignKey(User, on_delete=models.CASCADE)


	def __str__(self):
		"""Return a string representation of the model."""
		return self.text


class Entry(models.Model):
	"""Journal entry about a particular topic."""
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)


	class Meta:
		verbose_name_plural = 'entries'


	def __str__(self):
		"""Return a string representation of the model."""
		# Add ellipsis only if an entry is longer than 70 characters
		if len(self.text) > 70:
			return f"{self.text[:70]}..."

		else:
			return self.text
			

journpys/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''}

class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}
		

journpys/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
	"""Home page for journpy app."""
	return render(request, 'journpys/index.html')


# Use the @login_required decorator to ensure that users are logged in before 
# they access the topics page
@login_required
def topics(request):
	"""Show topics in JournPy."""
	topics = Topic.objects.filter(writer=request.user).order_by('date_added')
	context = {'topics' : topics}
	return render(request, 'journpys/topics.html', context)


@login_required
def topic(request, topic_id):
	"""Get a topic and all of its entry."""
	topic = get_object_or_404(Topic, id=topic_id)
	check_topic_writer(request, topic_id)
	entries = topic.entry_set.order_by('-date_added')
	context = {'topic': topic, 'entries': entries}
	return render(request, 'journpys/topic.html', context)


@login_required
def new_topic(request):
	"""Allow users to enter a new topic."""
	if request.method != 'POST':
		# No data submitted therefore create a blank form.
		form = TopicForm()
	else:
		# POST data submitted and process data.
		form = TopicForm(data=request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.writer = request.user
			new_topic.save()
			return redirect('journpys:topics')

	# Display a blank or invalid form.
	context = {'form': form}
	return render(request, 'journpys/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
	"""New entry for a topic"""
	topic = get_object_or_404(Topic, id=topic_id)
	check_topic_writer(request, topic_id)
	
	if request.method != 'POST':
		# No data submitted; create a blank form
		form = EntryForm()
	else:
		# POST and process data
		form = EntryForm(data=request.POST)

		if form.is_valid:
			new_entry = form.save(commit=False)
			# Set the topic attribute of new_entry to the topic pulled from
			# the database at the begining of the function
			new_entry.topic = topic
			new_entry.save()
			return redirect('journpys:topic', topic_id=topic_id)

	# Display a blank or invalid form.
	context = {'topic': topic, 'form': form}
	return render(request, 'journpys/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
	"""Edit an existing entry."""
	entry = get_object_or_404(Entry, id=entry_id)
	topic = entry.topic
	if topic.writer != request.user:
		raise Http404

	if request.method != 'POST':
		# Initial request; pre-fill form with the current entry.
		form = EntryForm(instance=entry)
	else:
		# POST data submitted; process data.
		form = EntryForm(instance=entry, data=request.POST)

		if form.is_valid():
			form.save()
			return redirect('journpys:topic', topic_id=topic.id)
	context = {'entry': entry, 'topic': topic, 'form': form}
	return render(request, 'journpys/edit_entry.html', context)


def check_topic_writer(request, topic_id):
	"""Check whether the writer of the topic matches the currently logged in 
		user. If not, raise an Http404 exception."""
	topic = Topic.objects.get(id=topic_id)
	if topic.writer != request.user:
		raise Http404


@login_required
def delete_topic(request, topic_id):
	"""Delete a topic and all of it's entries."""
	topic = get_object_or_404(Topic, id=topic_id)
	topic.delete()
	return redirect('journpys:topics')
	context = {'topic': topic}
	return render(request, 'journpys/delete_topic.html', context)


@login_required
def delete_entry(request, entry_id):
	"""Delete an existing entry."""
	entry = get_object_or_404(Entry, id=entry_id)
	topic = entry.topic
	entry.delete()
	return redirect('journpys:topic', topic_id=topic.id)
	context = {'entry': entry, 'topic': topic}
	return render(request, 'journpys/delete_entry.html', context)


def about(request):
	"""Display About page for JournPy."""
	return render(request, 'journpys/about.html')
	

journpys/templates/journpys/about.html
{% extends "journpys/base.html" %}

{% block page_header %}
<h1 class="text-success">About</h1>
{% endblock page_header %}

{% block content %}
<p class="lead font-italic">JournPy is an online learning platform that offers free
  tutorials on python. Users can learn how to write python programs and
  track their learning using the JournPy personal journal. Users can also
  make journal entries about other topics they are interested in. You can
  create new topics, add new entries, read and edit existing journal entries
  and also delete topics and entries.</p>
{% endblock content %}

journpys/templates/journpys/base.html
{% load bootstrap4 %}
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, 
    shrink-to-fit=no">
  <title>JournPy</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'journpys/journpy_icon.png' %}">
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
  {# Bootstrap Dropdown is built on the third-party library popper which provides dynamic positioning. #}
  {# Here, I include popper.min.js file before Bootstrap javascript or include #}
  {# bootstrap.bundle.min.js / bootstrap.bundle.js which contains Popper. #}
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
    integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT"
    crossorigin="anonymous"></script>
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-0 border">

    <a class="navbar-brand" href="{% url 'journpys:index' %}">
      <img src="{% static 'journpys/journpy_icon.png' %}" alt="JournPy" width="auto" height="40"></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
      aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">JPLearn</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'learnpython:lessons' %}">Learn Python</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item disabled" href="#">Learn Math</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'journpys:topics' %}">Personal Journal
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'journpys:about' %}">About
          </a>
        </li>
      </ul>
      <!-- login and registration links -->
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="navbar-text">Hello, {{ user.username }}.</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Log out
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register' %}">
            Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
        </li>
        {% endif %}
      </ul>
    </div>

  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>
</body>
{% include "main/includes/footer.html" %}

</html>

journpys/templates/journpys/delete_entry.html
{% extends "journpys/base.html" %}

<!-- The view function for this template redirects so there's no need to write
any code here because users won't see this page. -->

journpys/templates/journpys/delete_topic.html
{% extends "journpys/base.html" %}

<!-- The view function for this template redirects so there's no need to write
any code here because users won't see this page. -->

journpys/templates/journpys/edit_entry.html
{% extends "journpys/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2 class="text-success"><a href="{% url 'journpys:topic' topic.id %}" 
    class="text-reset">{{ topic }}</a></h2>
{% endblock page_header %}

{% block content %}
  <p>Edit entry:</p>

  <form method="post" action="{% url 'journpys:edit_entry' entry.id %}" 
    class="form">
  	{% csrf_token %}
  	{% bootstrap_form form %}
    {% buttons %}
  	  <button name="submit" class="btn btn-success">Save</button>
    {% endbuttons %}
  </form>

{% endblock content %}

journpys/templates/journpys/index.html
{% extends "journpys/base.html" %}

{% block page_header %}
<div class="jumbotron text-justify bg-white pb-0">
  <h1 class="display-2 text-success fw-bold">Stay informed with JournPy.</h1>
  <p class="lead font-italic">With JournPy, you can learn how to write python programs
    and track your learning using your personal journal. You can make
    journal entries for any topic you are learning about.
    You can also use this app to record news and events that occur in your
    daily life. Sign up and start learning today!</p>
  <div class="pt-2 pb-2">
    {% if user.is_authenticated %}
    <a class="btn btn-success" href="{% url 'journpys:topics' %}" role="button">Your Journal &raquo;</a>
    {% else %}
    <a class="btn btn-lg btn-success" href="{% url 'users:register' %}" role="button">Sign Up &raquo;</a>
    {% endif %}
  </div>
</div>
{% endblock page_header %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div col-sm-4>
      <div class="card p-0 m-0">
        <div class="row">
          <div class="col-sm-6">
            {% load static %}
            <img class="card-img" src="{% static 'journpys/leaf.jpg' %}" alt="Card image">
          </div>
          <div class="col-sm-6">
            <div class="card-body-right">
              <h3 class="card-title text-success">User friendliness</h3>
              <p class="card-text font-italic">JournPy can be easily used by anyone including
                children.</p>
              <h3 class="card-title text-success">Integrity</h3>
              <p class="card-text font-italic">Be rest assured that your data is safe
                and secure.</p>
              <h3 class="card-title text-success">Functionality</h3>
              <p class="card-text font-italic">Make daily entries into your journal and monitor
                your progress as you learn.</p>
              {% if user.is_authenticated %}
              <a class="btn btn-success" href="{% url 'journpys:topics' %}" role="button">Your Journal &raquo;</a><br />
              {% else %}
              <a class="btn btn-success" href="{% url 'users:register' %}" role="button">Sign Up &raquo;</a><br />
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

journpys/templates/journpys/new_entry.html
{% extends "journpys/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2 class="text-success"><a href="{% url 'journpys:topic' topic.id %}" 
    class="text-reset">{{ topic }}</a></h2>
{% endblock page_header %}

{% block content %}
  <p>Add an entry for "{{ topic }}":</p>
  <form method="post" action="{% url 'journpys:new_entry' topic.id %}" 
    class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-success">Add</button>
    {% endbuttons %}
</form>

{% endblock content %}

journpys/templates/journpys/new_topic.html
{% extends "journpys/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h1>Add a new topic:</h1>
{% endblock page_header %}

{% block content %}
  <form method = "post" action="{% url 'journpys:new_topic' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %} 
    {% buttons %}
      <button name="submit" class="btn btn-success">Add</button>
    {% endbuttons %}
  </form>

{% endblock content %}

journpys/templates/journpys/topic.html
{% extends 'journpys/base.html' %}

{% block page_header %}
  <h1>{{ topic }}</h1>
{% endblock page_header %}

{% block content %}
  <p class="text-success">
    <a href="{% url 'journpys:new_entry' topic.id %}" 
      class="text-reset">New entry</a>
  </p>
  
  {% for entry in entries %}
    <div class="card mb-3">
      <h5 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small class="text-success">
          <a href="{% url 'journpys:edit_entry' entry.id %}" 
            class="text-reset">Edit</a>
          <a href="{% url 'journpys:delete_entry' entry.id %}" 
            class="text-reset">Delete</a>
        </small>
      </h5>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>
  {% empty %}
    <p>There are no entries for this topic yet.</p>
  {% endfor %}

{% endblock content %}

journpys/templates/journpys/topics.html
{% extends "journpys/base.html" %}

{% block page_header %}
  <h1>Topics</h1>
  <p class="text-warning">Clicking 'Delete' permanently deletes the topic 
    and all the entries in it.</p>
{% endblock page_header %}

{% block content %}
  <ul>
  	{% for topic in topics %}
  	  <li><h5 class="text-success">
  	  	<a href="{% url 'journpys:topic' topic.id %}" 
          class="text-reset">{{ topic }}
        <a href="{% url 'journpys:delete_topic' topic.id %}" 
          class="text-warning">Delete</a></a>
  	  </h5></li>
  	{% empty %}
  	  <li><h5>No topics have been added yet.</h5></li>
  	{% endfor %}
  </ul>

  <h3 class="text-success"><a href="{% url 'journpys:new_topic' %}" 
    class="text-reset">New topic</a></h3>
 {% endblock content %}